adom_perception:
  ros__parameters:
    image_topic: /zed/zed_node/rgb/color/rect/image
    depth_topic: /zed/zed_node/depth/depth_registered
    mask_topic: /adom/perception/semantic_mask
    model_path: ""
    input_width: 640
    input_height: 384
    target_fps: 30.0
